manifest:
  defaults:
    revision: main
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: shiusu1010
      url-base: https://github.com/shiusu1010
  projects:
    - name: zmk
      remote: zmkfirmware
      # ▼ ここを main から v0.1 に変更！ ▼
      revision: v0.1
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: zmk-dongle-screen
      remote: shiusu1010
      revision: main
  self:
    path: config