manifest:
  defaults:
    revision: main
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: shiusu1010
      url-base: https://github.com/shiusu1010
    # ▼ 追加: Prospectorの配布元
    - name: carrefinho
      url-base: https://github.com/carrefinho
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: zmk-dongle-screen
      remote: shiusu1010
      revision: main
    # ▼ 追加: Prospectorモジュール本体
    - name: prospector-zmk-module
      remote: carrefinho
      revision: main
  self:
    path: config