# --- 画面表示はとりあえずオフ ---
CONFIG_ZMK_DISPLAY=n

# --- 入力機能 ---
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y

# 【重要】分割キーボード間でマウスデータを同期・転送する設定
CONFIG_ZMK_SPLIT_POINTING=y

# --- HID（PCへのマウス通知）の有効化 ---
CONFIG_ZMK_MOUSE=y

# --- 通信安定化 ---
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y